//----------------------------------------------------------------
// Generated by Excel Table exporter in 2018/9/7 - 18:07:04
//----------------------------------------------------------------


package table
{
    
    public class Instance
    {
        final public function get ID() : int { 
          return _data.ID;
        }

        final public function get Name() : String { 
          return _data.Name;
        }

        final public function get Description() : String { 
          return _data.Description;
        }

        final public function get IconName() : String { 
          return _data.IconName;
        }

        final public function get Chapter() : int { 
          return _data.Chapter;
        }

        private var _data:Object;
        
        public function Instance( data:Object ) : void 
        {
          this._data = data;
        
        }
   }
}

