/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class GameSceneUI extends Scene {

		override protected function createChildren():void {
			super.createChildren();
			loadScene("GameScene");

		}

	}
}