/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class LoginMenuUI extends Scene {
		public var start_btn:Button;
		public var rank_btn:Button;
		public var audio_clip:Clip;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Scene","props":{"width":750,"height":1334},"compId":1,"child":[{"type":"Image","props":{"y":0,"x":0,"width":750,"skin":"gameUI/all_bg.jpg","height":1334},"compId":4},{"type":"Button","props":{"y":855,"x":107,"width":536,"var":"start_btn","stateNum":1,"skin":"gameUI/startGame.png","sizeGrid":"5,6,6,5","labelSize":96,"labelColors":"#000000","height":165},"compId":3},{"type":"Text","props":{"y":266,"x":0,"width":747,"text":"合到10","height":154,"fontSize":140,"color":"#ffffff","align":"center","runtime":"laya.display.Text"},"compId":9},{"type":"Button","props":{"y":1119,"x":235,"var":"rank_btn","stateNum":2,"skin":"gameUI/btn_rank.png"},"compId":10},{"type":"Clip","props":{"y":1119,"x":416,"var":"audio_clip","skin":"gameUI/clip_audio.png","clipY":2,"clipX":1},"compId":13},{"type":"Text","props":{"y":433,"x":3,"width":753,"text":"最高记录","height":84,"fontSize":60,"color":"#ffffff","align":"center","runtime":"laya.display.Text"},"compId":14},{"type":"UIView","props":{"pageData":{"type":"View","props":{"width":100,"runtime":"script.CNumberView","height":102,"y":517,"x":323.5,"name":"numberView"},"compId":1,"child":[{"type":"List","props":{"y":0,"x":0,"width":79,"var":"list","repeatY":1,"repeatX":3,"height":102},"compId":3}],"loadList":[],"loadList3D":[]}},"compId":15},{"type":"WXOpenDataViewer","props":{"y":1087,"x":22,"width":200,"iconSign":"wx","height":200,"runtime":"laya.ui.WXOpenDataViewer"},"compId":16}],"loadList":["gameUI/all_bg.jpg","gameUI/startGame.png","gameUI/btn_rank.png","gameUI/clip_audio.png","NumberView.scene"],"loadList3D":[],"components":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}