/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class MessageViewUI extends View {
		public var txt:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":400,"height":100},"compId":1,"child":[{"type":"Label","props":{"y":16.5,"var":"txt","text":"labellabel","styleSkin":"comp/label.png","height":67,"fontSize":48,"color":"#ffffff","centerX":0},"compId":2}],"loadList":["comp/label.png"],"loadList3D":[],"components":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}