/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class NumberViewUI extends View {
		public var list:List;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":100,"runtime":"script.CNumberView","height":102},"compId":1,"child":[{"type":"List","props":{"y":0,"x":0,"width":79,"var":"list","repeatY":1,"repeatX":3,"height":102},"compId":3}],"loadList":[],"loadList3D":[],"components":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}