/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class RankViewUI extends Dialog {
		public var player_list:List;
		public var return_btn:Button;
		public var qun_rank_btn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Dialog","props":{"width":750,"height":1334},"compId":1,"child":[{"type":"Sprite","props":{"width":750,"texture":"gameUI/bg_frame.jpg","height":1334},"compId":5},{"type":"Image","props":{"y":161,"x":12,"width":726,"skin":"gameUI/ass.png","sizeGrid":"36,29,49,39","rotation":0,"height":947},"compId":10},{"type":"Sprite","props":{"y":-27,"x":140,"texture":"gameUI/score_title.png"},"compId":11},{"type":"Sprite","props":{"y":121,"x":252,"texture":"gameUI/friend_rank_title.png"},"compId":12},{"type":"Text","props":{"y":207,"x":273.5,"width":203,"text":"每周一0点清零","height":48,"fontSize":30,"color":"#ffffff","runtime":"laya.display.Text"},"compId":13},{"type":"List","props":{"y":255,"x":51,"width":658,"var":"player_list","spaceY":4,"repeatY":6,"repeatX":1,"height":804},"compId":15},{"type":"Button","props":{"y":1174,"x":51,"var":"return_btn","stateNum":2,"skin":"gameUI/btn_refresh.png"},"compId":16},{"type":"Button","props":{"y":1182.5,"x":243.5,"var":"qun_rank_btn","stateNum":1,"skin":"gameUI/btn_look_qun.png"},"compId":17}],"loadList":["gameUI/bg_frame.jpg","gameUI/ass.png","gameUI/score_title.png","gameUI/friend_rank_title.png","gameUI/btn_refresh.png","gameUI/btn_look_qun.png"],"loadList3D":[],"components":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}