/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class RankItemUI extends View {
		public var bg_normal:Sprite;
		public var rank_1_img:Sprite;
		public var rank_2_img:Sprite;
		public var rank_3_img:Sprite;
		public var head_bg:Sprite;
		public var head_icon:Image;
		public var name_txt:Text;
		public var score_txt:Text;
		public var rank_txt:Text;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":658,"height":95},"compId":1,"child":[{"type":"Sprite","props":{"y":0,"x":0,"var":"bg_normal","texture":"gameUI/rank_item_bg.png"},"compId":2},{"type":"Clip","props":{"y":0,"x":0,"skin":"gameUI/clip_rank_item_light.png","name":"selectBox","index":1,"clipY":2,"clipX":1},"compId":12},{"type":"Sprite","props":{"y":2.5,"x":15,"var":"rank_1_img","texture":"gameUI/rank1.png"},"compId":4},{"type":"Sprite","props":{"y":2.5,"x":15,"var":"rank_2_img","texture":"gameUI/rank2.png"},"compId":5},{"type":"Sprite","props":{"y":2.5,"x":15,"var":"rank_3_img","texture":"gameUI/rank3.png"},"compId":6},{"type":"Sprite","props":{"y":7.5,"x":101,"var":"head_bg","texture":"gameUI/rank_head_bg.png"},"compId":7},{"type":"Image","props":{"y":8,"x":103,"width":28,"var":"head_icon","height":34},"compId":8},{"type":"Text","props":{"y":29,"x":198.5,"width":261,"var":"name_txt","text":"玩家名字","height":37,"fontSize":30,"color":"#000000","runtime":"laya.display.Text"},"compId":9},{"type":"Text","props":{"y":29,"x":470,"width":176,"var":"score_txt","text":"999999","height":37,"fontSize":30,"color":"#000000","align":"center","runtime":"laya.display.Text"},"compId":10},{"type":"Text","props":{"y":29,"x":10,"width":72,"var":"rank_txt","text":"22","height":37,"fontSize":30,"color":"#000000","align":"center","runtime":"laya.display.Text"},"compId":11}],"loadList":["gameUI/rank_item_bg.png","gameUI/clip_rank_item_light.png","gameUI/rank1.png","gameUI/rank2.png","gameUI/rank3.png","gameUI/rank_head_bg.png"],"loadList3D":[],"components":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}