//----------------------------------------------------------------
// Generated by Excel Table exporter in 2018/9/7 - 18:07:04
//----------------------------------------------------------------


package table
{
    
    public class InstanceType
    {
        final public function get ID() : int { 
          return _data.ID;
        }

        final public function get Name() : String { 
          return _data.Name;
        }

        final public function get AutoFight() : int { 
          return _data.AutoFight;
        }

        private var _data:Object;
        
        public function InstanceType( data:Object ) : void 
        {
          this._data = data;
        
        }
   }
}

