/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class ResultViewUI extends Dialog {
		public var reset_btn:Button;
		public var top_number_img:Image;
		public var score_txt:Label;
		public var top_score_txt:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Dialog","props":{"y":0,"x":75,"width":600,"height":1000,"autoDestroyAtClosed":false},"compId":1,"child":[{"type":"Image","props":{"y":0,"x":0,"width":600,"skin":"comp/img_bg.png","name":"bg","height":1000,"sizeGrid":"29,6,7,5"},"compId":8},{"type":"Button","props":{"y":811,"x":0,"width":137,"var":"reset_btn","skin":"comp/button.png","name":"reset_btn","label":"重新开始","height":72},"compId":2},{"type":"Button","props":{"y":811,"x":400,"width":137,"skin":"comp/button.png","name":"share_btn","label":"分享","height":72},"compId":3},{"type":"Image","props":{"y":576,"x":277,"var":"top_number_img","name":"top_number_img"},"compId":4},{"type":"Label","props":{"y":145,"x":95.5,"width":409,"var":"score_txt","text":"分数","styleSkin":"comp/label.png","name":"score_txt","height":67,"fontSize":48,"color":"#ffffff","align":"center"},"compId":5},{"type":"Label","props":{"y":248,"x":95.5,"width":409,"var":"top_score_txt","text":"最高分","styleSkin":"comp/label.png","name":"top_score_txt","height":67,"fontSize":48,"color":"#ffffff","align":"center"},"compId":6}],"loadList":["comp/img_bg.png","comp/button.png","comp/label.png"],"loadList3D":[],"components":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}