//----------------------------------------------------------------
// Generated by Excel Table exporter in 2018/8/22 - 12:17:24
//----------------------------------------------------------------


package KOF;

public class Buff
{

    public int ID;
    public String Name;
    public String Description;
    public String IconName;
    public String SFXName;
    public int ProfessionConstrain;
    public int GroupID;
    public int Type;
    public DateTime DueDateTime;
    public float Duration;
    public int ActingType;
    public int DOT;
    public int DOT_HP;
    public int DOT_RP;
    public int AvailableTimes;
    public int TriggerTiming;
    public float TriggerChance;
    public int TriggerSkillID;
    public int SkillTargetType;
    public int NumRounds;
    public int HP;
    public float HP_Percent;
    public int PhysicalAP;
    public float PhysicalAP_Percent;
    public int PhysicalDP;
    public float PhysicalDP_Percent;
    public int MagicalAP;
    public float MagicalAP_Percent;
    public int MagicalDP;
    public float MagicalDP_Percent;
    public int SpiritualAP;
    public float SpiritualAP_Percent;
    public int SpiritualDP;
    public float SpiritualDP_Percent;
    public float StrikeChance;
    public float StrikeChance_Percent;
    public float StrikeStrength;
    public float StrikeStrength_Percent;
    public float HitBackChance;
    public float HitBackChance_Percent;
    public int DecreaseAP;
    public float DecreaseAP_Percent;
    public int RestoredRP;
    public float RestoredRP_Percent;
    public float FirstHandChance;
    public float FirstHandChance_Percent;
    public bool Fear;
    public bool Enchanted;
    public bool Sleep;
    public bool Immune;
    public bool Paralyzed;
    public bool Invincible;
    public float TeamFirstHandChance;
}
