//----------------------------------------------------------------
// Generated by Excel Table exporter in 2018/9/7 - 18:07:04
//----------------------------------------------------------------


package table;

public class Chapter
{

    public int ID;
    public int Type;
    public String Name;
    public int OpenLevel;
    public int Reward;
}
