//----------------------------------------------------------------
// Generated by Excel Table exporter in 2018/9/7 - 18:07:04
//----------------------------------------------------------------


package table;

public class Instance
{

    public int ID;
    public String Name;
    public String Description;
    public String IconName;
    public int Chapter;
}
