//----------------------------------------------------------------
// Generated by Excel Table exporter in 2018/9/7 - 18:07:04
//----------------------------------------------------------------


package table;

public class InstanceType
{

    public int ID;
    public String Name;
    public int AutoFight;
}
