/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package game.ui {
	import laya.ui.*;import laya.display.*; 

	public class GameSceneUI extends Scene {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Scene","props":{"width":750,"runtime":"script.MyScene","height":1334},"compId":1,"child":[{"type":"Script","props":{"runtime":"script.MyControl"},"compId":5},{"type":"Sprite","props":{"texture":"scene/bg.png","name":"bg"},"compId":6},{"type":"Sprite","props":{"y":243,"x":-504,"texture":"scene/light.png","name":"rain"},"compId":7},{"type":"Image","props":{"y":64,"x":39,"width":672,"skin":"scene/frame.png","height":1206,"sizeGrid":"8,4,12,3"},"compId":10},{"type":"Sprite","props":{"width":750,"name":"sceneLayer","height":1334},"compId":11},{"type":"Label","props":{"y":161,"x":292.5,"width":165,"text":"9999","styleSkin":"comp/label.png","strokeColor":"#5b0900","stroke":4,"name":"curScore","height":48,"fontSize":48,"color":"#ffffff","align":"center"},"compId":14},{"type":"Sprite","props":{"width":750,"name":"uiLayer","height":1334},"compId":13}],"loadList":["scene/bg.png","scene/light.png","scene/frame.png","comp/label.png"],"loadList3D":[],"components":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}