/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package game.ui {
	import laya.ui.*;import laya.display.*; 

	public class NumberViewUI extends View {
		public var list:List;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":300,"runtime":"script.CNumberView","height":102},"compId":1,"child":[{"type":"List","props":{"var":"list","repeatY":1,"repeatX":3},"compId":3,"child":[{"type":"Clip","props":{"y":0,"x":0,"skin":"gameUI/clip_number1.png","name":"render","clipY":1,"clipX":10},"compId":2}],"components":[]}],"loadList":["gameUI/clip_number1.png"],"loadList3D":[],"components":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}